### PR TITLE
Fix hydration of components inside `<Suspense>`

### LINKED ISSUE #2400: Transition issue with React Suspense
**What package within Headless UI are you using?**

**@headlessui/react**

**What version of that package are you using?**

`"@headlessui/react": "^1.7.13"`

**What browser are you using?**

 Chrome

**Reproduction URL**

Github repro: https://github.com/jorisre/headlessui-suspense-issue

**Describe your issue**

When using two `<Transition />` components through `<Portal />` _(or other)_ in combination of React `<Suspense />` we get a React rendering issue _(see screen below)_.

I tried to fix it directly inside the @headlessui/react without success. It seems the issue is related to [`useServerHandoffComplete`](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/hooks/use-server-handoff-complete.ts) and [`env.ts`](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/utils/env.ts). If someone have a hint that helps me to fix it ✌🏻 

Screenshot 2023-03-29 at 12 51 15

ezgif com-optimize

**Steps to reproduce:**

1. Clone the repo https://github.com/jorisre/headlessui-suspense-issue
2. Run `npm install`
3. And `npm run dev`
4. Then go to http://localhost:3000 and open the browser console to see the error

### PR DESCRIPTION
**Pull request by thecrypticace**
This is a redo of #2633 but with a more targeted fix for just React 18+

Previously, when dealing with SSR, we had a hook that would basically force a re-render of all components on page load. This also used some global state so we didn't unnecessarily cause re-renders for components that were mounting after the page had already loaded.

However, because `<Suspense>` delays hydration this is no longer a viable solution. I've implemented a targeted fix by (mis)using the `useSyncExternalStore` API. You can provide a `getServerSnapshot` callback that only runs on the server AND in the browser but only _when hydrating_. This gives us just enough info to know when hydration is happening.

I've slotted that into our `useServerHandoffComplete()` hook to handle the `<Suspense>` case. I'm also using wildcard imports, a `"useSyncExternalStore" in React` guard, and a lazy closure to ensure that bundlers don't statically analyze this in a way that errors for React < 18.

Fixes #2400

### CODE REVIEW

File: packages/@headlessui-react/src/hooks/use-server-handoff-complete.ts [hunk 1]
```diff
@@ -1,8 +1,43 @@
...
+/**
+ * This is used to determine if we're hydrating in React 18.
+ *
+ * The `useServerHandoffComplete` hook doesn't work with `<Suspense>`
+ * because it assumes all hydration happens at one time during page load.
+ *
+ * Given that the problem only exists in React 18 we can rely
+ * on newer APIs to determine if hydration is happening.
+ *
+ * @returns
```
Comment (RobinMalfait) [inline packages/@headlessui-react/src/hooks/use-server-handoff-complete.ts:13]: We can probably drop this since we are using TypeScript already?

File: packages/playground-react/pages/suspense/portal.tsx [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+  return { default: MyComponent }
+})
+
+export default function Index() {
+  return (
+    <div>
+      <h1>@headlessui/react & Suspense</h1>
+
+      <Portal>
```
Comment (RobinMalfait) [inline packages/playground-react/pages/suspense/portal.tsx:21]: Can we position/style it a tiny bit? While testing I just noticed this and was super confused: 
image


Didn't realise I had to scroll down 😅

**Review by RobinMalfait — COMMENTED** [review]
Apart from a few comments this is looking great.

Was testing it with the Dialogs and Transition components as well because we had some issues with those last time we were solving this. But this all seems to work as expected now.

Nice!

File: packages/playground-react/pages/suspense/portal.tsx (hunk 2 above)
Comment (thecrypticace) [reply packages/playground-react/pages/suspense/portal.tsx:21]: Ah yeah I was testing it the components directly. Suspense * useRouter don't work well together. But yeah I can do that.

Comment (thecrypticace) [reply packages/playground-react/pages/suspense/portal.tsx:21]: Updated

File: packages/@headlessui-react/src/hooks/use-server-handoff-complete.ts (hunk 1 above)
Comment (thecrypticace) [reply packages/@headlessui-react/src/hooks/use-server-handoff-complete.ts]: Updated

**Review by RobinMalfait — APPROVED** [review]
